skip_tags: true
image: Visual Studio 2017
configuration: Release

skip_commits:
  message: /\[WIP\]/

install:
  - nuget restore

assembly_info:
  patch: false


on_failure:
  - ps: 7z a "WorkingTree.zip"
  - ps: Push-AppveyorArtifact WorkingTree.zip

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  verbosity: minimal

deploy:
- provider: GitHub
  auth_token:
    secure: zSOGlECwz3ZYOh1TRGkP5mrljlAgtlxaVfGlieOfgv3YkO/e3s1NX/HQkQefhYis
  on:
    branch: master
- provider: NuGet
  api_key:
    secure: TwWHVdjcJdEIGimzcMeGdskjvEfDYM/R1FFZWAvkQQbz13lf16QxhiXSTGTJO0zW
  on:
    branch: master